apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-configmap
data:
  backbase-realm.json: |-
{{ .Files.Get "support-files/backbase-realm.json" | indent 4}}
  backbase-users-0.json: |-
{{ .Files.Get "support-files/backbase-users-0.json" | indent 4}}