global:
  # rollme will ensure that the pods are recreated even without changing the image tags, more info  https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
  podExtraAnnotations:
    rollme: "{{ randAlphaNum 5 | quote }}"
  chartName: authentication-dev

  app:
    metadata:
      tier: ips
      public: true

    image:
      registry: repo.backbase.com/backbase-docker-releases    
      tag: IPS-1.13.0-no-production
  imagePullSecrets:
    - name: bbrepo-credentials


  jwt:
    enabled: true
    existingSecret: "backbase-env-jwt"
    # SIG_SECRET_KEY_fromSecret: false
    # USERCTX_KEY_fromSecret: false

  env:
  #   "EUREKA_CLIENT_ENABLED": "false"
  #   "SPRING_CLOUD_KUBERNETES_ENABLED": "true"
  #   "SPRING_CLOUD_KUBERNETES_LOADBALANCER_MODE": "SERVICE"
  #   "SPRING_AUTOCONFIGURE_EXCLUDE": "org.springframework.cloud.netflix.eureka.loadbalancer.LoadBalancerEurekaAutoConfiguration"

    "EUREKA_CLIENT_ENABLED": "true"
    "SPRING_CLOUD_KUBERNETES_ENABLED": "false"
    "SPRING_CLOUD_KUBERNETES_RELOAD_ENABLED": "false"
    "spring.autoconfigure.exclude": ""

  activemq:
    enabled: true
    checkEnabled: false
    host: backbase-env-activemq
    existingSecret: backbase-env-activemq

  registry:
    host: registry
    enabled: true
    checkEnabled: false

authentication-dev:
  app:
    name: authentication-dev
    image:
      repository: authentication-dev
  service:
    enabled: true
    nameOverride: auth

  livenessProbe:
    enabled: true

  readinessProbe:
    enabled: true

#try your new users
  env:
    AUTHENTICATION_USERS_RESOURCE: file:///auth-dev/backbase-auth-dev-users.json
  customFilesPath: /auth-dev/
  customFiles:
    backbase-auth-dev-users.json: |
      [ {
      "username" : "popo",
      "password" : "{noop}popo",
      "roles" : [ "USER", "group_user(USER)" ]
      }, {
      "username" : "caca",
      "password" : "{noop}caca",
      "roles" : [ "USER", "group_user(USER)" ]
      } ]