global:
  # rollme will ensure that the pods are recreated even without changing the image tags, more info  https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
  podExtraAnnotations:
    rollme: "{{ randAlphaNum 5 | quote }}"
  chartName: ips-edge

  app:
    metadata:
      tier: ips
    image:
      registry: repo.backbase.com/backbase-docker-releases
      tag: IPS-1.12.1
  imagePullSecrets:
    - name: bbrepo-credentials

edge:
  app :
    name: edge
    image:
      repository: edge
    resources:
      memory:
        ram: 1024
        containerReserve: 128
      cpu:
        minShares: 200
        maxShares: 1000

  livenessProbe:
    enabled: true

  readinessProbe:
    enabled: true

  ingress:
    enabled: false

  service:
    enabled: true
    nameOverride: edge

  registry:
    host: registry    
    enabled: true
    checkEnabled: false

  env:
    GATEWAY_ACTUATOR_USER: "admin"
    GATEWAY_ACTUATOR_PASSWORD: "admin"